### ISSUE TITLE
Login with contentdb yields "invalid_username"

### ISSUE THREAD

**Issue by Desour** [minetest-ch/lemmy.minetest.ch#6]
I tried to log in (first time) via ContentDB, but got this after authorizing:
```
set user profile error: 400 Bad Request: invalid_username
```

Link to my contentdb profile, if it matters: https://content.minetest.net/users/Desour/
I was renamed once (from "DS-Minetest"). And my displayed name ("DS") is quite short.

**Comment by BuckarooBanzay** [comment]
Thanks for the report :+1:

The lemmy-oauth-companion tried to sync your displayname, which is 2 characters long to the lemmy instance, but the required length for a displayname is 3 :/

Fixed it here: https://github.com/minetest-ch/lemmy-oauth-companion/commit/a71d71943dc418c7e9bde8026702393d14b665d1 (should be deployed shortly)

**Comment by Desour** [comment]
Thanks! Login works now. :)
